name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.25.0'
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: wget https://github.com/bytecodealliance/javy/releases/download/v1.2.0/javy-x86_64-linux-v1.2.0.gz
      - run: gzip -d javy-x86_64-linux-v1.2.0.gz
      - run: chmod +x javy-x86_64-linux-v1.2.0
      - run: npm install
      - run: npx tsc --noEmit
      - run: npx esbuild --bundle src/app.ts --tree-shaking=true --format=esm --target=es2020 --outfile=out.js
      - run: mkdir dist
      - name: set binary name
        id: bin_name
        run: echo "bin_name=sqlc-gen-typescript-0.1.4-${{ github.sha }}.wasm" >> $GITHUB_OUTPUT
      - run: ./javy-x86_64-linux-v1.2.0 compile out.js -o dist/${{ steps.bin_name.outputs.bin_name }}
      - run: shasum -a 256 dist/${{ steps.bin_name.outputs.bin_name }} | awk '{ print $1}' > dist/${{ steps.bin_name.outputs.bin_name }}.sha256
      - uses: actions/upload-artifact@v4
        with:
          name: sqlc-gen-typescript
          path: dist
